version: "3.7"
services:
  frentend:
    build: ./frontend
    ports:
      - 5000:3000
    restart: always
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27900:27017
    restart: always
    volumes:
      - vdatamongo:/data/db
volumes:
  vdatamongo: