version: "3.7"
services:
  frentend:
    build: ./front-end
    ports:
      - 5000:3000
    restart: always
    
  authservice:
    build: ./back-end/auth-service
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    
  emailservice:
    build: ./back-end/email-service
    ports:
      - 3005:3000
    restart: always
    depends_on:
      - mongo
  orderservice:
    build: ./back-end/order-service
    ports:
      - 3003:3000
    restart: always
    depends_on:
      - mongo
  productservice:
    build: ./back-end/product-service
    ports:
      - 3002:3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27900:27017
    restart: always
    volumes:
      - vdatamongo:/data/db
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  gateway:
    image: nginx
    volumes:
      - ./Gateway/api.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
volumes:
  vdatamongo: